# Generated by Django 2.0 on 2018-02-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250, unique=True, verbose_name='Заголовок')),
                ('news_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('news_text', models.TextField(unique=True, verbose_name='Текст статьи')),
                ('news_liked', models.IntegerField(verbose_name='Like')),
                ('news_category', models.CharField(choices=[('policy', 'Политика'), ('society', 'Общество'), ('economy', 'Экономика'), ('world', 'В мире'), ('sport', 'Спорт'), ('incedent', 'Происшествия'), ('culture', 'Культура'), ('tech', 'Технологии'), ('science', 'Наука')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новости',
                'db_table': 'newsbase',
            },
        ),
    ]
