# Generated by Django 2.0 on 2018-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsbase',
            name='news_author',
        ),
        migrations.AddField(
            model_name='newsbase',
            name='news_authors',
            field=models.CharField(choices=[('Mamaev_Oleg', 'Мамаев Олег'), ('Maksimova_Marina', 'Максимова Марина'), ('Doncova_Dariya', 'Донцова Дарья')], default='', max_length=30, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_liked',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
        migrations.AlterModelTable(
            name='newsbase',
            table=None,
        ),
    ]
