# Generated by Django 2.0 on 2018-02-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180212_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbase',
            name='news_views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
