# Generated by Django 2.0 on 2018-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsbase_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='news_text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
