# Generated by Django 2.0 on 2018-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180227_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbase',
            name='news_pic',
            field=models.ImageField(blank=True, null=True, upload_to='news/pic', verbose_name='Изображение'),
        ),
    ]
