# Generated by Django 2.0 on 2018-03-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180302_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic1',
            field=models.ImageField(blank=True, upload_to='news/pic', verbose_name='Изображение1'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic2',
            field=models.ImageField(blank=True, upload_to='news/pic', verbose_name='Изображение2'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic3',
            field=models.ImageField(blank=True, upload_to='news/pic', verbose_name='Изображение3'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic4',
            field=models.ImageField(blank=True, upload_to='news/pic', verbose_name='Изображение4'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic5',
            field=models.ImageField(blank=True, upload_to='news/pic', verbose_name='Изображение5'),
        ),
    ]
