# Generated by Django 2.0 on 2018-03-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180302_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic1',
            field=models.ImageField(upload_to='news/pic', verbose_name='Изображение1'),
        ),
    ]
