# Generated by Django 2.0 on 2018-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180302_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Заголовок')),
                ('datetime', models.DateTimeField(default=0, verbose_name='Дата и время публикации')),
                ('text', models.TextField(verbose_name='Статья')),
                ('image', models.URLField(verbose_name='Ссылка на изображение')),
                ('cop_url', models.URLField(verbose_name='Ссылка на статью РИА')),
            ],
            options={
                'verbose_name': 'Тест риа новости',
            },
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic1',
            field=models.ImageField(upload_to='news/pic/%Y/%m/%d', verbose_name='Изображение1'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic2',
            field=models.ImageField(blank=True, upload_to='news/pic/%Y/%m/%d', verbose_name='Изображение2'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic3',
            field=models.ImageField(blank=True, upload_to='news/pic/%Y/%m/%d', verbose_name='Изображение3'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic4',
            field=models.ImageField(blank=True, upload_to='news/pic/%Y/%m/%d', verbose_name='Изображение4'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='news_pic5',
            field=models.ImageField(blank=True, upload_to='news/pic/%Y/%m/%d', verbose_name='Изображение5'),
        ),
    ]
