# Generated by Django 2.0 on 2018-03-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20180315_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='my_city',
        ),
    ]
